
steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_RESPOSITORY}/${_IMAGE}', '.']

images:
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_RESPOSITORY}/${_IMAGE}'

substitutions:
  _LOCATION: "us-central1"
  _RESPOSITORY: "terra-run"
  _IMAGE: "terrarun"
  _PROJECT_ID: "terra-run-build"

  

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', '${gcr.io/terra-run-build/github.com/wowmind/terraform-cloudrun-cloud-build:$COMMIT_SHA}', '.']
- name: gcr.io/cloud-builders/docker
  args: ['push', '${gcr.io/terra-run-build/github.com/wowmind/terraform-cloudrun-cloud-build:$COMMIT_SHA}]
